version: "3.4"
services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNzc3NjJlNmM1YTkzZWJlMjVlYTQ4OWYyZjZjZjIzY2QiLCJ0IjoiY2EwNGE4Y2UtYzc5ZS00NWJiLWEwOTgtYjUxYTQzNWRjNGQ1IiwicyI6Ik16aGhaVFV4T1RndE9UaGhZaTAwTW1VeExUZ3hNMlV0TXpNMk1XVTVZakU1T0dRMCJ9
    networks:
      main:
        ipv4_address: 10.0.92.4
  client:
    container_name: viteClient
    build:
      context: ../client
      dockerfile: Dockerfile
    environment:
      - VITE_ORIGIN=https://cncmusic.ml
      - VITE_GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
      - VITE_SCHOOL_NAME=Colegiul National Alexandru Ioan Cuza
    volumes:
      - ./dist:/app/dist
  server:
    container_name: expressServer
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ORIGIN=https://cncmusic.ml
      - DB_URL=mongodb://db:27017/pauzeMuzicale
      - COOKIE_SECRET=28901d2f-c0ba-4ebc-aa44-2a43ae4e9528
      - JWT_SECRET=f47cb99d-cb96-44a2-8577-05a47b0e6138
      - GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
      - GOOGLE_DOMAIN_CHECK=@cnaic.ro
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - client
    networks:
      main:
        ipv4_address: 10.0.92.3
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    networks:
      main:
        ipv4_address: 10.0.92.2
networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "10.0.92.0/24"
